spring:
  application:
    name: Producer Service
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topic: test-topic